import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,ArrowUpRight,Search,Radio,Pause,Play,RefreshCw,SlidersHorizontal,Headphones,Globe,Check,ExternalLink,X,Volume2,VolumeX,Wifi,Disc3} from 'lucide-react';
import {Analytics} from '@vercel/analytics/react';
import {SpeedInsights} from '@vercel/speed-insights/react';
import './style.css';
import './timeline.css';
import './insights.css';
import './header-layout.css';
import {mentionActivity} from '../lib/story-intel.js';
const sourceNames=['Google News','Stereogum','Pitchfork','Billboard'];
const sourceIds=['google','stereogum','pitchfork','billboard'];
const FEED_CACHE_KEY='lyfe-feed-v2';
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const save=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value))}catch{}};
const ago=(date)=>{const minutes=Math.max(0,Math.floor((Date.now()-Date.parse(date))/60000));return minutes<1?'Just now':minutes<60?`${minutes}m ago`:minutes<1440?`${Math.floor(minutes/60)}h ago`:`${Math.floor(minutes/1440)}d ago`};
const sourceStatus=(source)=>{if(!source)return 'Not checked yet';if(source.status==='ok')return 'Online';const reason=source.reason==='rate_limited'?'Rate limited':source.reason==='blocked'?'Access blocked':source.reason==='timeout'?'Timed out':'Unavailable';const seconds=Math.max(0,Math.ceil((Date.parse(source.retryAt)-Date.now())/1000));return reason+(seconds>0?' · retry in '+Math.ceil(seconds/60)+'m':' · retry pending')+(source.status==='stale'?' · cached posts':'');};
const sourceDomains={google:'news.google.com',stereogum:'stereogum.com',pitchfork:'pitchfork.com',billboard:'billboard.com'};
function PublisherLogo({source,publisherUrl,publisher}){
 let domain=sourceDomains[source];
 if(publisherUrl){try{const url=new URL(publisherUrl);if(['https:','http:'].includes(url.protocol))domain=url.hostname;}catch{}}
 else if(source==='google'&&publisher&&/^(?:[a-z0-9-]+\.)+[a-z]{2,}$/i.test(publisher))domain=publisher;
 const [failed,setFailed]=useState(false);
 return failed||!domain?<Globe size={18} aria-hidden="true"/>:<img className="publisher-logo" src={'https://www.google.com/s2/favicons?domain='+encodeURIComponent(domain)+'&sz=64'} alt="" loading="lazy" referrerPolicy="no-referrer" onError={()=>setFailed(true)}/>;
}
function PostMedia({item}){
 const [failed,setFailed]=useState(false);
 return <a className="post-media" href={item.url} target="_blank" rel="noreferrer" aria-label={item.media.kind==='video'?'Watch video':'Open image'}>
 {!failed&&<img src={item.media.thumbnail} alt="Post preview" loading="lazy" decoding="async" referrerPolicy="no-referrer" onError={()=>setFailed(true)}/>} 
 <span>{item.media.kind==='video'?<><Play size={18}/>Watch video</>:failed?'View media':'Open image'}<ArrowUpRight size={15}/></span>
 </a>;
}
function ReleaseTimeline(){
 const [releases,setReleases]=useState([]);const [loading,setLoading]=useState(true);const [attempt,setAttempt]=useState(0);
 useEffect(()=>{setLoading(true);fetch('/api/releases').then(response=>response.ok?response.json():Promise.reject()).then(data=>setReleases(data.items||[])).catch(()=>setReleases([])).finally(()=>setLoading(false))},[attempt]);
 return <section className="release-timeline" aria-labelledby="release-timeline-heading"><div className="timeline-heading"><div><span className="eyebrow">DISCOGRAPHY</span><h2 id="release-timeline-heading">Release timeline</h2></div><span className="timeline-note">Newest to oldest</span></div>{loading?<p className="timeline-empty">Loading releases...</p>:releases.length?<div className="timeline-track">{releases.map(release=><a className="release-point" href={release.url} target="_blank" rel="noreferrer" key={release.id}>{release.artwork&&<img src={release.artwork} alt="" loading="lazy"/>}<div className="release-copy"><time dateTime={release.releaseDate}>{new Date(release.releaseDate).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})}</time><strong>{release.title}</strong><span>{release.album}</span></div></a>)}</div>:<p className="timeline-empty">Release data is temporarily unavailable. <button onClick={()=>setAttempt(value=>value+1)}>Retry</button></p>}</section>;
}
function RightNow({items}){
 const recent=items.filter(item=>Date.now()-Date.parse(item.publishedAt)<72*60*60*1000);
 const story=(recent.length?recent:items).slice().sort((a,b)=>(b.clusterSize||1)-(a.clusterSize||1)||b.importance-a.importance||Date.parse(b.publishedAt)-Date.parse(a.publishedAt))[0];
 if(!story)return null;
 return <section className="right-now"><div className="right-now-head"><span className="eyebrow">RIGHT NOW</span><span className={'verification '+(story.sourceCount>1?'multiple':'reported')}>{story.sourceCount>1?'MULTIPLE OUTLETS REPORTING':'REPORTED'}</span></div><h2><a href={story.url} target="_blank" rel="noreferrer">{story.title} <ArrowUpRight size={20}/></a></h2><p>{story.description||'A developing story is being tracked across the news.'}</p><div><strong>{story.sourceCount||1} sources</strong><span>{story.sourceNames?.join(' · ')}</span><span>· Last update {ago(story.publishedAt)}</span></div></section>;
}
function MentionGraph({items}){
 const activity=mentionActivity(items);const max=Math.max(1,...activity.map(day=>day.count));
 return <section className="mention-card"><div><span className="eyebrow">MENTION ACTIVITY</span><strong>7 days</strong></div><div className="mention-bars">{activity.map(day=><span key={day.date} title={`${day.count} stories`} style={{height:`${Math.max(8,day.count/max*100)}%`}}/> )}</div></section>;
}
function IntelPanel({items,data}){
 const cutoff=Date.now()-24*60*60*1000;const recent=items.filter(item=>Date.parse(item.publishedAt)>=cutoff);const sources=new Set(recent.flatMap(item=>(item.sources||[{id:item.source}]).map(source=>(source.name||source.id).toLowerCase().replace(/[^a-z0-9]/g,''))));const discussed=recent.slice().sort((a,b)=>(b.clusterSize||1)-(a.clusterSize||1))[0];
 return <section className="intel-panel"><div className="intel-kicker">LAST 24 HOURS</div><div className="intel-stats"><div><strong>{recent.reduce((total,item)=>total+(item.clusterSize||1),0)}</strong><span>mentions</span></div><div><strong>{recent.length}</strong><span>new stories</span></div><div><strong>{data?.officialSite?.changed?1:0}</strong><span>official update</span></div><div><strong>{sources.size}</strong><span>sources reporting</span></div></div>{discussed&&<div className="most-discussed"><span>Most discussed</span><strong>{discussed.title}</strong></div>}</section>;
}
function SourceStatusPanel({data,onClose}){
 return <div className="status-panel" role="dialog" aria-label="Source status"><div className="status-panel-head"><strong>Source status</strong><button aria-label="Close source status" onClick={onClose}><X size={18}/></button></div>{data.sources.map(source=><div className="status-row" key={source.id}><div><strong>{source.name}</strong><span>{source.status==='ok'?'Online':source.reason||'Unavailable'}</span></div><div><span>{source.responseMs?`${source.responseMs} ms`:'—'}</span><span>{source.articlesFound??'—'} articles</span><small>{source.lastSuccessAt?new Date(source.lastSuccessAt).toLocaleString():'No successful fetch'}</small></div></div>)}{data.officialSite&&<div className="official-change"><strong>{data.officialSite.changed?'OFFICIAL SITE UPDATED':'Official site checked'}</strong><span>{data.officialSite.changed?'Music, tour or news links changed.':new Date(data.officialSite.lastCheckedAt).toLocaleString()}</span></div>}</div>;
}
function FeedInsights({data,sortMode,setSortMode,statusOpen,setStatusOpen}){
 return <div className="feed-insights"><div className="sort-toggle"><button className={sortMode==='newest'?'active':''} onClick={()=>setSortMode('newest')}>NEWEST</button><button className={sortMode==='important'?'active':''} onClick={()=>setSortMode('important')}>IMPORTANT</button></div><button className="status-button" onClick={()=>setStatusOpen(true)}><Activity size={14}/> {data?`${data.sources.filter(source=>source.status==='ok').length}/${data.sources.length} sources reachable`:'Checking sources'}</button>{statusOpen&&data&&<SourceStatusPanel data={data} onClose={()=>setStatusOpen(false)}/>}</div>;
}
function App(){
 const [data,setData]=useState(()=>read(FEED_CACHE_KEY,null));const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [paused,setPaused]=useState(false);const [query,setQuery]=useState('');const [tab,setTab]=useState('All updates');const [publisher,setPublisher]=useState('all');const [settings,setSettings]=useState(false);const [compact,setCompact]=useState(()=>read('lyfe-compact',false));const [clock,setClock]=useState(new Date());const active=useRef(false);
 const [soundEnabled,setSoundEnabled]=useState(false);const [soundError,setSoundError]=useState('');const [statusOpen,setStatusOpen]=useState(false);const [sortMode,setSortMode]=useState('newest');const audio=useRef(null);const soundOn=useRef(false);
 function chime(){
  const context=audio.current;if(!soundOn.current || context?.state!=='running')return;
  try{const now=context.currentTime;[660,880].forEach((frequency,index)=>{const oscillator=context.createOscillator();const gain=context.createGain();const start=now+index*0.12;oscillator.frequency.value=frequency;gain.gain.setValueAtTime(0,start);gain.gain.linearRampToValueAtTime(0.07,start+0.015);gain.gain.exponentialRampToValueAtTime(0.001,start+0.2);oscillator.connect(gain);gain.connect(context.destination);oscillator.start(start);oscillator.stop(start+0.22);oscillator.onended=()=>{oscillator.disconnect();gain.disconnect()};});}catch{ /* Audio must never interrupt the news feed. */ }
 }
 async function toggleSound(){
  if(soundOn.current){soundOn.current=false;setSoundEnabled(false);return;}
  try{const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)throw Error();audio.current ||= new AudioContext();await audio.current.resume();if(audio.current.state!=='running')throw Error();soundOn.current=true;setSoundEnabled(true);setSoundError('');chime();}catch{setSoundError('Sound could not start. Try enabling it again in this browser.');}
 }
 useEffect(()=>()=>{soundOn.current=false;audio.current?.close().catch(()=>{});},[]);
 async function refresh(){if(active.current)return;active.current=true;setBusy(true);try{const response=await fetch('/api/feed');if(!response.ok)throw Error();const next=await response.json();next.items=next.items.filter(item=>sourceIds.includes(item.source));next.sources=next.sources.filter(source=>sourceIds.includes(source.id));const previous=read(FEED_CACHE_KEY,null);const failed=new Set(next.sources.filter(s=>s.status!=='ok').map(s=>s.id));const ids=new Set(next.items.map(i=>i.id));next.items=[...next.items,...(previous?.items||[]).filter(i=>failed.has(i.source)&&!ids.has(i.id))].sort((a,b)=>Date.parse(b.publishedAt)-Date.parse(a.publishedAt)).slice(0,160);setData(next);save(FEED_CACHE_KEY,next);setError(next.stale?'Sources are taking a break. Showing the last available updates.':'');if(!next.stale&&previous&&next.items.some(item=>!previous.items.some(old=>old.id===item.id)))chime();}catch{setError('Could not reach the feeds. Previously loaded stories stay available.')}finally{active.current=false;setBusy(false)}}
 useEffect(()=>{refresh()},[]);
 useEffect(()=>{if(paused)return;const timer=setInterval(()=>{if(!document.hidden)refresh()},60000);return()=>clearInterval(timer)},[paused]);
 useEffect(()=>{const timer=setInterval(()=>setClock(new Date()),30000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{save('lyfe-compact',compact)},[compact]);
 useEffect(()=>{const close=e=>{if(e.key==='Escape')setSettings(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[]);
 const items=(data?.items||[]).filter(item=>sourceIds.includes(item.source));
 const tabMatches=item=>tab==='All updates'||(tab==='Music'?['Music','Release','Feature','Album','Single','Video'].includes(item.category):tab==='Live'?['Live','Tour'].includes(item.category):tab==='News'?['News','Interview','Rumor'].includes(item.category):item.category===tab);
 const filtered=items.filter(i=>tabMatches(i)&&(publisher==='all'||i.source===publisher)&&`${i.title} ${i.publisher}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sortMode==='important'?b.importance-a.importance:Date.parse(b.publishedAt)-Date.parse(a.publishedAt));
 const columns=[{id:'updates',title:publisher!=='all'?sourceNames[sourceIds.indexOf(publisher)]:query.trim()?'Search results':tab,items:filtered}];
 const ok=data?.sources.filter(s=>sourceIds.includes(s.id)&&s.status==='ok').length||0;
    return <div className="app"><header className="topbar"><a className="brand" href="/">YEAT TRACKER</a><div className="top-right"><div className={'live-badge '+(paused?'is-paused':'')}><span/>{paused?'PAUSED':error?'OFFLINE CACHE':busy?'CHECKING':'AUTO REFRESH'}</div><button className="icon-button" aria-label="Display settings" onClick={()=>setSettings(!settings)}><SlidersHorizontal size={18}/></button></div></header>
    <div className="workspace"><aside className="sidebar"><div className="side-label">YOUR RADAR</div><button className="nav-item selected" onClick={()=>{setTab('All updates');setPublisher('all');setQuery('')}}><Radio size={18}/>Live feed<span className="count">{data?.items.length||0}</span></button><div className="side-separator"/><div className="side-label source-heading">SOURCES <span>{ok}/{sourceNames.length}</span></div><button className={'source-row '+(publisher==='all'?'active':'')} onClick={()=>setPublisher('all')}><Globe size={16}/>All sources<span className="source-count">{sourceNames.length}</span></button>{sourceNames.map((name,i)=>{const id=sourceIds[i];const source=data?.sources.find(s=>s.id===id);const status=source?.status;return <button className={'source-row '+(publisher===id?'active':'')} key={id} onClick={()=>setPublisher(id)}><span className={'source-avatar source-'+i}><PublisherLogo source={id}/></span><span className="source-text">{name}{source&&status!=='ok'&&<small>{sourceStatus(source)}</small>}</span><span title={sourceStatus(source)} className={'health '+(status==='ok'?'healthy':'')}/></button>})}<a className="official" href="https://www.yeatofficial.com/" target="_blank" rel="noreferrer">Yeat official <ArrowUpRight size={16}/></a><section className="pulse"><div className="side-label">FEED STATUS <Activity size={15}/></div><div><span>Sources online</span><strong>{ok}<small> / {sourceNames.length}</small></strong></div><div><span>Check interval</span><strong>60 seconds</strong></div><div><span>Source cache</span><strong>5 minutes</strong></div><div><span>Last checked</span><strong>{data?ago(data.updatedAt):'Connecting…'}</strong></div></section><p className="disclaimer">Made for the fans.<br/>Not affiliated with Yeat or his team.</p></aside>
 <main><ReleaseTimeline/><RightNow items={items}/><IntelPanel items={items} data={data}/><MentionGraph items={items}/><FeedInsights data={data} sortMode={sortMode} setSortMode={setSortMode} statusOpen={statusOpen} setStatusOpen={setStatusOpen}/>
 <div className="feed-toolbar"><div className="tabs">{['All updates','Music','Live','News'].map(t=><button key={t} className={tab===t?'current':''} onClick={()=>setTab(t)}>{t}{t==='All updates'&&<span>{data?.items.length||0}</span>}</button>)}</div><div className="feed-actions"><button className={soundEnabled?'sound-enabled':''} title={soundEnabled?'Mute new-story sound':'Enable new-story sound'} aria-label={soundEnabled?'Mute new-story sound':'Enable new-story sound'} aria-pressed={soundEnabled} onClick={toggleSound}>{soundEnabled?<Volume2 size={16}/>:<VolumeX size={16}/>}</button><button title={paused?'Resume automatic refresh':'Pause automatic refresh'} aria-label={paused?'Resume feed':'Pause feed'} onClick={()=>setPaused(!paused)}>{paused?<Play size={16}/>:<Pause size={16}/>}</button><button title="Refresh feed" aria-label="Refresh feed" disabled={busy} onClick={refresh}><RefreshCw size={16} className={busy?'spin':''}/></button></div></div>
 <div className="mobile-controls"><select aria-label="Filter by source" value={publisher} onChange={e=>setPublisher(e.target.value)}><option value="all">All sources</option>{sourceNames.map((name,i)=><option key={name} value={sourceIds[i]}>{name}</option>)}</select></div><div className="search-row"><div className="search"><Search size={17}/><input aria-label="Search updates" placeholder="Search the feed…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Clear search" onClick={()=>setQuery('')}><X size={14}/></button>}</div><span>{sortMode==='important'?'IMPORTANT FIRST':'NEWEST FIRST'}</span></div>
 {soundError&&<div className="notice" role="status">{soundError}</div>}
 {error&&<div className="notice" role="status">{error} <button onClick={refresh}>Retry</button></div>}
 {paused&&<div className="notice">Automatic refresh paused. <button onClick={()=>setPaused(false)}>Resume feed</button></div>}
 {publisher!=='all'&&<div className="filter-label">Showing {data?.sources.find(s=>s.id===publisher)?.name||publisher}<button onClick={()=>setPublisher('all')}>Clear filter <X size={12}/></button></div>}
 <div className="feed-columns single-feed" aria-busy={busy}>{columns.map(column=><section className="feed-column" key={column.id} aria-labelledby={column.id+'-heading'}><div className="column-heading"><h2 id={column.id+'-heading'}>{column.title}</h2><span>{column.items.length} updates</span></div><div className="column-status"/><div className="feed">{column.items.length?column.items.map(item=><article className={'story '+(compact?'compact':'')} key={item.id}><div className="story-top"><span className={'publisher-icon '+item.source}><PublisherLogo source={item.source} publisherUrl={item.publisherUrl} publisher={item.publisher}/></span><div><strong>{item.publisher}</strong><span className="story-meta">{item.source==='google'?'via Google News':'Direct RSS'}{data?.sources.find(s=>s.id===item.source)?.status!=='ok'&&<span>· Cached</span>}<span>·</span><time dateTime={item.publishedAt} title={new Date(item.publishedAt).toLocaleString()}>{ago(item.publishedAt)}</time></span></div><span className={'category '+item.category.toLowerCase()}>{item.category==='Music'?<Disc3 size={12}/>:item.category==='Live'?<Headphones size={12}/>:<Globe size={12}/>} {item.category}</span></div><a className="story-title" href={item.url} target="_blank" rel="noreferrer">{item.title}<ArrowUpRight size={23}/></a>{item.description&&<p className="story-description">{item.description}</p>}{!compact&&item.media?.thumbnail&&<PostMedia key={item.media.thumbnail} item={item}/ >}{!compact&&<div className="story-bottom"><span className="topic"># YEAT</span><div><a href={item.url} target="_blank" rel="noreferrer">Read story <ArrowUpRight size={14}/></a></div></div>}</article>):<div className="empty"><Radio size={28}/><h3>{busy?'Loading updates…':'No '+column.title.toLowerCase()+' updates.'}</h3><p>{busy?'Checking sources.':query||publisher!=='all'||tab!=='All updates'?'No posts match the current filters.':'Checking again every 60 seconds.'}</p></div>}</div></section>)}</div>
 </main></div>
 <footer><span><Wifi size={13}/>{error?'Cached mode':busy?'Checking sources':`${ok} sources reachable`}</span><span>{clock.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span></footer>
 {settings&&<div className="settings" role="dialog" aria-label="Display settings"><div><strong>Display settings</strong><button aria-label="Close settings" onClick={()=>setSettings(false)}><X size={18}/></button></div><label><span>Sound for new stories</span><input type="checkbox" checked={soundEnabled} onChange={toggleSound}/></label><p>Enable sound once per visit. A short chime plays when a refresh finds new stories.</p><label><span>Compact feed</span><input type="checkbox" checked={compact} onChange={e=>setCompact(e.target.checked)}/></label><p>Display preferences stay in this browser.</p></div>}
 <Analytics />
 <SpeedInsights />
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
