import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,ArrowUpRight,Search,Radio,Pause,Play,RefreshCw,SlidersHorizontal,Headphones,Globe,Check,ExternalLink,X,Volume2,VolumeX,Wifi,Disc3} from 'lucide-react';
import './style.css';
const sourceNames=['Google News','Stereogum','Pitchfork','Billboard','Reddit · r/yeat_'];
const sourceIds=['google','stereogum','pitchfork','billboard','reddit'];
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const save=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value))}catch{}};
const ago=(date)=>{const minutes=Math.max(0,Math.floor((Date.now()-Date.parse(date))/60000));return minutes<1?'Just now':minutes<60?`${minutes}m ago`:minutes<1440?`${Math.floor(minutes/60)}h ago`:`${Math.floor(minutes/1440)}d ago`};
const sourceStatus=(source)=>{if(!source)return 'Not checked yet';if(source.status==='ok')return 'Online';const reason=source.reason==='rate_limited'?'Rate limited':source.reason==='blocked'?'Access blocked':source.reason==='timeout'?'Timed out':'Unavailable';const seconds=Math.max(0,Math.ceil((Date.parse(source.retryAt)-Date.now())/1000));return reason+(seconds>0?' · retry in '+Math.ceil(seconds/60)+'m':' · retry pending')+(source.status==='stale'?' · cached posts':'');};
const sourceDomains={google:'news.google.com',stereogum:'stereogum.com',pitchfork:'pitchfork.com',billboard:'billboard.com',reddit:'reddit.com'};
function PublisherLogo({source,publisherUrl,publisher}){
 let domain=sourceDomains[source];
 if(publisherUrl){try{const url=new URL(publisherUrl);if(['https:','http:'].includes(url.protocol))domain=url.hostname;}catch{}}
 else if(source==='google'&&publisher&&/^(?:[a-z0-9-]+\.)+[a-z]{2,}$/i.test(publisher))domain=publisher;
 const [failed,setFailed]=useState(false);
 return failed||!domain?<Globe size={18} aria-hidden="true"/>:<img className="publisher-logo" src={'https://www.google.com/s2/favicons?domain='+encodeURIComponent(domain)+'&sz=64'} alt="" loading="lazy" referrerPolicy="no-referrer" onError={()=>setFailed(true)}/>;
}
function PostMedia({item}){
 const [failed,setFailed]=useState(false);
 return <a className="post-media" href={item.url} target="_blank" rel="noreferrer" aria-label={item.media.kind==='video'?'Watch video on Reddit':'Open image post on Reddit'}>
 {!failed&&<img src={item.media.thumbnail} alt="Reddit post preview" loading="lazy" decoding="async" referrerPolicy="no-referrer" onError={()=>setFailed(true)}/>}
 <span>{item.media.kind==='video'?<><Play size={18}/>Watch on Reddit</>:failed?'View media on Reddit':'Open image on Reddit'}<ArrowUpRight size={15}/></span>
 </a>;
}
function App(){
 const [data,setData]=useState(()=>read('lyfe-feed',null));const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [paused,setPaused]=useState(false);const [query,setQuery]=useState('');const [tab,setTab]=useState('All updates');const [publisher,setPublisher]=useState('all');const [settings,setSettings]=useState(false);const [compact,setCompact]=useState(()=>read('lyfe-compact',false));const [clock,setClock]=useState(new Date());const active=useRef(false);
 const [soundEnabled,setSoundEnabled]=useState(false);const [soundError,setSoundError]=useState('');const audio=useRef(null);const soundOn=useRef(false);
 function chime(){
  const context=audio.current;if(!soundOn.current || context?.state!=='running')return;
  try{const now=context.currentTime;[660,880].forEach((frequency,index)=>{const oscillator=context.createOscillator();const gain=context.createGain();const start=now+index*0.12;oscillator.frequency.value=frequency;gain.gain.setValueAtTime(0,start);gain.gain.linearRampToValueAtTime(0.07,start+0.015);gain.gain.exponentialRampToValueAtTime(0.001,start+0.2);oscillator.connect(gain);gain.connect(context.destination);oscillator.start(start);oscillator.stop(start+0.22);oscillator.onended=()=>{oscillator.disconnect();gain.disconnect()};});}catch{ /* Audio must never interrupt the news feed. */ }
 }
 async function toggleSound(){
  if(soundOn.current){soundOn.current=false;setSoundEnabled(false);return;}
  try{const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)throw Error();audio.current ||= new AudioContext();await audio.current.resume();if(audio.current.state!=='running')throw Error();soundOn.current=true;setSoundEnabled(true);setSoundError('');chime();}catch{setSoundError('Sound could not start. Try enabling it again in this browser.');}
 }
 useEffect(()=>()=>{soundOn.current=false;audio.current?.close().catch(()=>{});},[]);
 async function refresh(){if(active.current)return;active.current=true;setBusy(true);try{const response=await fetch('/api/feed');if(!response.ok)throw Error();const next=await response.json();next.items=next.items.filter(item=>sourceIds.includes(item.source));next.sources=next.sources.filter(source=>sourceIds.includes(source.id));const previous=read('lyfe-feed',null);const failed=new Set(next.sources.filter(s=>s.status!=='ok').map(s=>s.id));const ids=new Set(next.items.map(i=>i.id));next.items=[...next.items,...(previous?.items||[]).filter(i=>failed.has(i.source)&&!ids.has(i.id))].sort((a,b)=>Date.parse(b.publishedAt)-Date.parse(a.publishedAt)).slice(0,160);setData(next);save('lyfe-feed',next);setError(next.stale?'Sources are taking a break. Showing the last available updates.':'');if(!next.stale)chime();}catch{setError('Could not reach the feeds. Previously loaded stories stay available.')}finally{active.current=false;setBusy(false)}}
 useEffect(()=>{refresh()},[]);
 useEffect(()=>{if(paused)return;const timer=setInterval(()=>{if(!document.hidden)refresh()},60000);return()=>clearInterval(timer)},[paused]);
 useEffect(()=>{const timer=setInterval(()=>setClock(new Date()),30000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{save('lyfe-compact',compact)},[compact]);
 useEffect(()=>{const close=e=>{if(e.key==='Escape')setSettings(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[]);
 const items=(data?.items||[]).filter(item=>sourceIds.includes(item.source));
 const filtered=items.filter(i=>(tab==='All updates'||i.category===tab)&&(publisher==='all'||i.source===publisher)&&`${i.title} ${i.publisher}`.toLowerCase().includes(query.toLowerCase()));
 const splitFeed=tab==='All updates'&&publisher==='all'&&!query.trim();
 const columns=splitFeed?[{id:'news',title:'News',items:filtered.filter(item=>!item.source.startsWith('reddit'))},{id:'reddit',title:'Reddit',items:filtered.filter(item=>item.source.startsWith('reddit'))}]:[{id:'filtered',title:publisher!=='all'?sourceNames[sourceIds.indexOf(publisher)]:query.trim()?'Search results':tab,items:filtered}];
 const ok=data?.sources.filter(s=>sourceIds.includes(s.id)&&s.status==='ok').length||0;
 return <div className="app"><header className="topbar"><a className="brand" href="/">YEAT TRACKER</a><div className="top-right"><div className={'live-badge '+(paused?'is-paused':'')}><span/>{paused?'PAUSED':error?'OFFLINE CACHE':busy?'CHECKING':'AUTO REFRESH'}</div><button className="icon-button" aria-label="Display settings" onClick={()=>setSettings(!settings)}><SlidersHorizontal size={18}/></button></div></header>
 <div className="workspace"><aside className="sidebar"><div className="side-label">YOUR RADAR</div><button className="nav-item selected" onClick={()=>{setTab('All updates');setPublisher('all');setQuery('')}}><Radio size={18}/>Live feed<span className="count">{data?.items.length||0}</span></button><div className="side-separator"/><div className="side-label source-heading">SOURCES <span>{ok}/{sourceNames.length}</span></div><button className={'source-row '+(publisher==='all'?'active':'')} onClick={()=>setPublisher('all')}><Globe size={16}/>All sources<span className="source-count">{sourceNames.length}</span></button>{sourceNames.map((name,i)=>{const id=sourceIds[i];const source=data?.sources.find(s=>s.id===id);const status=source?.status;return <button className={'source-row '+(publisher===id?'active':'')} key={id} onClick={()=>setPublisher(id)}><span className={'source-avatar source-'+i}><PublisherLogo source={id}/></span><span className="source-text">{name}{source&&status!=='ok'&&<small>{sourceStatus(source)}</small>}</span><span title={sourceStatus(source)} className={'health '+(status==='ok'?'healthy':'')}/></button>})}<a className="official" href="https://www.yeatofficial.com/" target="_blank" rel="noreferrer">Yeat official <ArrowUpRight size={16}/></a><section className="pulse"><div className="side-label">FEED STATUS <Activity size={15}/></div><div><span>Sources online</span><strong>{ok}<small> / {sourceNames.length}</small></strong></div><div><span>Refresh interval</span><strong>30 seconds</strong></div><div><span>Last checked</span><strong>{data?ago(data.updatedAt):'Connecting…'}</strong></div></section><p className="disclaimer">Made for the fans.<br/>Not affiliated with Yeat or his team.</p></aside>
 <main>
 <div className="feed-toolbar"><div className="tabs">{['All updates','Music','Live','News','Community'].map(t=><button key={t} className={tab===t?'current':''} onClick={()=>setTab(t)}>{t}{t==='All updates'&&<span>{data?.items.length||0}</span>}</button>)}</div><div className="feed-actions"><button className={soundEnabled?'sound-enabled':''} title={soundEnabled?'Mute refresh sound':'Enable refresh sound'} aria-label={soundEnabled?'Mute refresh sound':'Enable refresh sound'} aria-pressed={soundEnabled} onClick={toggleSound}>{soundEnabled?<Volume2 size={16}/>:<VolumeX size={16}/>}</button><button title={paused?'Resume automatic refresh':'Pause automatic refresh'} aria-label={paused?'Resume feed':'Pause feed'} onClick={()=>setPaused(!paused)}>{paused?<Play size={16}/>:<Pause size={16}/>}</button><button title="Refresh feed" aria-label="Refresh feed" disabled={busy} onClick={refresh}><RefreshCw size={16} className={busy?'spin':''}/></button></div></div>
 <div className="mobile-controls"><select aria-label="Filter by source" value={publisher} onChange={e=>setPublisher(e.target.value)}><option value="all">All sources</option>{sourceNames.map((name,i)=><option key={name} value={sourceIds[i]}>{name}</option>)}</select></div><div className="search-row"><div className="search"><Search size={17}/><input aria-label="Search updates" placeholder="Search the feed…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Clear search" onClick={()=>setQuery('')}><X size={14}/></button>}</div><span>NEWEST FIRST</span></div>
 {soundError&&<div className="notice" role="status">{soundError}</div>}
 {error&&<div className="notice" role="status">{error} <button onClick={refresh}>Retry</button></div>}
 {paused&&<div className="notice">Automatic refresh paused. <button onClick={()=>setPaused(false)}>Resume feed</button></div>}
 {publisher!=='all'&&<div className="filter-label">Showing {data?.sources.find(s=>s.id===publisher)?.name||publisher}<button onClick={()=>setPublisher('all')}>Clear filter <X size={12}/></button></div>}
 <div className={'feed-columns'+(splitFeed?'':' single-feed')} aria-busy={busy}>{columns.map(column=><section className="feed-column" key={column.id} aria-labelledby={column.id+'-heading'}><div className="column-heading"><h2 id={column.id+'-heading'}>{column.title}</h2><span>{column.items.length} updates</span></div><div className="column-status">{(column.id==='reddit'||(!splitFeed&&(tab==='All updates'||tab==='Community')&&(publisher==='all'||publisher.startsWith('reddit'))))&&data?.sources.filter(source=>source.id==='reddit'&&(publisher==='all'||source.id===publisher)&&source.status!=='ok').map(source=><p key={source.id}>{source.name.replace('Reddit · ','')}: {sourceStatus(source)}</p>)}</div><div className="feed">{column.items.length?column.items.map(item=><article className={'story '+(compact?'compact':'')} key={item.id}><div className="story-top"><span className={'publisher-icon '+item.source}><PublisherLogo source={item.source} publisherUrl={item.publisherUrl} publisher={item.publisher}/></span><div><strong>{item.publisher}</strong><span className="story-meta">{item.source.startsWith('reddit')?(item.author || 'Community post'):item.source==='google'?'via Google News':'Direct RSS'}{data?.sources.find(s=>s.id===item.source)?.status!=='ok'&&<span>· Cached</span>}<span>·</span><time dateTime={item.publishedAt} title={new Date(item.publishedAt).toLocaleString()}>{ago(item.publishedAt)}</time></span></div><span className={'category '+item.category.toLowerCase()}>{item.category==='Music'?<Disc3 size={12}/>:item.category==='Live'?<Headphones size={12}/>:<Globe size={12}/>} {item.category}</span></div><a className="story-title" href={item.url} target="_blank" rel="noreferrer">{item.title}<ArrowUpRight size={23}/></a>{!compact&&item.media?.thumbnail&&<PostMedia key={item.media.thumbnail} item={item}/ >}{!compact&&<div className="story-bottom"><span className="topic"># YEAT</span><div><a href={item.url} target="_blank" rel="noreferrer">{item.source.startsWith('reddit')?'View discussion':'Read story'} <ArrowUpRight size={14}/></a></div></div>}</article>):<div className="empty"><Radio size={28}/><h3>{busy?'Loading updates…':'No '+column.title.toLowerCase()+' updates.'}</h3><p>{busy?'Checking sources.':query||publisher!=='all'||tab!=='All updates'?'No posts match the current filters.':'Checking again every 30 seconds.'}</p></div>}</div></section>)}</div>
 </main></div>
 <footer><span><Wifi size={13}/>{error?'Cached mode':busy?'Checking sources':`${ok} sources reachable`}</span><span>{clock.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span></footer>
 {settings&&<div className="settings" role="dialog" aria-label="Display settings"><div><strong>Display settings</strong><button aria-label="Close settings" onClick={()=>setSettings(false)}><X size={18}/></button></div><label><span>Sound on refresh</span><input type="checkbox" checked={soundEnabled} onChange={toggleSound}/></label><p>Enable sound once per visit. A short chime plays after each successful refresh, even when there are no new posts.</p><label><span>Compact feed</span><input type="checkbox" checked={compact} onChange={e=>setCompact(e.target.checked)}/></label><p>Display preferences stay in this browser.</p></div>}
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
